- name: Large Integration Playbook
  hosts: servera*
  gather_facts: false
  tasks:
    - name: Import/Static/Pre-Process LDAP Task File
      ansible.builtin.import_tasks:
        file: tasks/ldap_tasks.yml
      when: meme is not defined

    - name: Include/Dynamic/Runtime Oracle Task File
      ansible.builtin.include_tasks:
        file: tasks/oracle_tasks.yml
      when: meme is not defined

    - name: Loop Task File Include Only
      # ansible.builtin.import_tasks:
      ansible.builtin.include_tasks:
        file: "{{ item }}"
      loop:
        - tasks/ldap_tasks.yml
        - tasks/oracle_tasks.yml


- name: Import Variable Playbook
  ansible.builtin.import_playbook: variable_demo.yml

- name: Import Multiple Playbook
  ansible.builtin.import_playbook: multiple_play.yml
