---
# tasks file for security_server

- name: Install Security Package
  ansible.builtin.dnf:
    name: "{{ security_server_package }}"
    state: present
  notify:
    - Security Package Install
    - Security Service

- name: Open Firewall Port
  ansible.posix.firewalld:
    service: "{{ security_server_port }}"
    permanent: true
    state: enabled
    immediate: true
  notify:
    - Security Port Open
    - Security Service
